
version: '3.4'

services:
  paythebill:
    image: paythebill
    build:
      context: .
      dockerfile: PayTheBill/Dockerfile
    volumes:
      - "./appsettings.json:/app/appsettings.json"
    labels:
        crono: "@daily"

  crono:
    image: hudsonventura/crono:latest
    restart: always
    volumes:
        - "./docker-compose.yml:/app/docker-compose.yml"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment: 
        - TIMEZONE=America/Cuiaba
        - WAIT=10